# Tarea 2
## Carlos Herrera
### 28 sept 2018

## Diagonales de una matriz

In [2]:
import math
import numpy as np

In [31]:
prueba = np.array([[11,12,13,14],
                   [21,22,23,24],
                   [31,32,33,34],
                   [41,42,43,44]])
prueba #Hago una matriz que contiene sus "indices"

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34],
       [41, 42, 43, 44]])

In [43]:
len(prueba)

4

In [33]:
np.size(prueba)

16

In [65]:
prueba.shape #DImensiones nxn

(4, 4)

In [39]:
prueba[0,0]

11

In [50]:
diag = [] #Creo lista vacía donde iré pegando las diagonales
#Funciona únicamente para matrices cuadradas
for ii in range(len(prueba)):
    diag.append(prueba[ii,ii])

diag
    

[11, 22, 33, 44]

In [22]:
matriz4 = np.random.rand(4,4) # Matriz aleatoria de 4x4
matriz4

array([[0.85908424, 0.27742185, 0.78824517, 0.7575111 ],
       [0.1512052 , 0.59410972, 0.96099045, 0.73280074],
       [0.62543627, 0.70401837, 0.73314335, 0.13979762],
       [0.32096353, 0.81809912, 0.04246517, 0.74179561]])

In [52]:
np.size(matriz4 ,0) 
np.size(matriz4, 1) #(matriz, 0=  filas/ 1 = columnas)

4

In [64]:
matriz = np.random.rand(10,10) ## Cree una matriz de nxn
diag = [] #Creo lista vacía donde iré pegando las diagonales
#Funciona únicamente para matrices cuadradas
for ii in range(len(matriz)):
    diag.append(matriz[ii,ii])

print("La diagonal es:")
diag

La diagonal es:


[0.7632523796800424,
 0.8760549713240349,
 0.4893786753974947,
 0.9141251240547872,
 0.5254764411108441,
 0.3647688268455672,
 0.058023734967584506,
 0.11961011017989986,
 0.3857443334843068,
 0.7047572423120441]

In [56]:
matriz


array([[0.39539774, 0.1341037 , 0.63428161, 0.56983009, 0.9826627 ,
        0.77670679, 0.92660864, 0.42288368, 0.28012869, 0.91301753],
       [0.81878965, 0.69822308, 0.71385806, 0.11853511, 0.46264372,
        0.69057287, 0.49763654, 0.84734714, 0.24431006, 0.54518701],
       [0.62349272, 0.69787623, 0.29219055, 0.23658377, 0.9922248 ,
        0.22640635, 0.15019207, 0.86595964, 0.86554549, 0.27430846],
       [0.25434279, 0.63757324, 0.0692318 , 0.59378223, 0.38722954,
        0.35283337, 0.60103762, 0.94719866, 0.98336583, 0.09098851],
       [0.44603203, 0.34386294, 0.98516028, 0.75004356, 0.62623582,
        0.036697  , 0.26775888, 0.50768129, 0.24651464, 0.32760643],
       [0.88447138, 0.04440073, 0.73233559, 0.58408677, 0.39700673,
        0.1065942 , 0.17170843, 0.54672627, 0.20145322, 0.36598013],
       [0.66168679, 0.37053315, 0.37343855, 0.94985573, 0.1180057 ,
        0.86967759, 0.64761598, 0.49674214, 0.47277241, 0.90666051],
       [0.57075029, 0.4768648 , 0.7753967

## Método de Newton - Krylov

In [71]:
import scipy

In [72]:
from scipy import linalg

In [74]:
from scipy import optimize

In [67]:
def g(x, y):
    return (x**2 - 2)*(y**2 - 3)

In [70]:
np.r_[3.,7.]

array([3., 7.])

In [76]:
optimize.newton_krylov?