## Escribir un código que extraiga los elementos de la diagonal de una matriz cuadrada


In [156]:
import numpy as np

def diag (Matrix):
    diag =[]
    row_size = len(Matrix)
    for i in range(0,row_size):
        diag.append(Matrix[i][i])
    return diag

B= np.diag(range(7,17))
print B
A = diag(B)
A

[[ 7  0  0  0  0  0  0  0  0  0]
 [ 0  8  0  0  0  0  0  0  0  0]
 [ 0  0  9  0  0  0  0  0  0  0]
 [ 0  0  0 10  0  0  0  0  0  0]
 [ 0  0  0  0 11  0  0  0  0  0]
 [ 0  0  0  0  0 12  0  0  0  0]
 [ 0  0  0  0  0  0 13  0  0  0]
 [ 0  0  0  0  0  0  0 14  0  0]
 [ 0  0  0  0  0  0  0  0 15  0]
 [ 0  0  0  0  0  0  0  0  0 16]]


[7, 8, 9, 10, 11, 12, 13, 14, 15, 16]

## Escribir una función que encuentre los ceros de una función utilizando el método de Newton-Krylov

El problema que teníamos en clase es que estabamos utilizando mal la funcion, utilizando la línea :

 optimize.newton_krylov(g(4), np.r_[3., 7.])
 
 El primer argumento de esta función debe ser la función a la cual se le quieren encontrar las raíces, no debe estar evaluada (pues es lo que el método hará), el segundo argumento debe de ser un array que representa la primera aproximación de la solución. Por tanto, al corregirlo se obtienen los ceros de la función :

In [157]:
def g(x):
    return (x**2 - 2)*(5**2 - 3)
optimize.newton_krylov(g, np.r_[1., 7.])

array([1.41421356, 1.41421356])

Utilizando el resultado anterior si evaluamos la función "g" en este valor obtenemosun valor muy cercano a un cero (computacional), como se muestra a continuación:

In [158]:
print g(1.2)
print g(1.41)
print g(1.41421356)

-12.32
-0.2618
-1.4766677614e-07
