# Tarea 2
Diana Islas Flores

Problema 1: hacer programa que extraiga la diagonal de una matriz cuadrada 

In [1]:
import numpy as np

m = np.array(range(1,101)).reshape(10, 10)
print m

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


La siguiente funcion hace un array que obtenga los valores de la diagonal. Si los indices de cada elemento de la matriz cuadrada estan dados por (i,j)(es decir m[i,j] es el elemento del renglon i y la columna j de la matriz), la diagonal de la matriz tiene los indices iguales (j = i). Por lo tanto, la funcion da los elementos m[i,i] de la matriz. 

In [2]:
def diag_print(m):
    b = np.array( [m[i,i] for i in xrange(10)])
    return b

In [3]:
c = diag_print(m)
print c

[  1  12  23  34  45  56  67  78  89 100]


.


Problema 2: optimize de scipy para funcion de dos variables

Matematicamente, no se puede encontrar los ceros de una funcion de dos variables sin tener una constante. Es decir, queremos ver donde cruzan los ejes por lo tanto encontrar donde cruza el eje x, y = 0 y obtener el cero para f(x,0)(que es funcion de una variable) y para ver donde cruza el eje y, x = 0 y se obtiene el cero para f(0,y). Por lo tanto, para python y scipy, no hay funcion de dos variables. La siguiente funcion calcula los ceros para cada eje como se explico anteriormente.

In [4]:
import scipy.optimize as optimize

def ceros(g,x0,y0):
    def g_x0(x,y = 0):
        return g(x,y)
    def g_y0(y,x = 0):
        return g(x,y)
    a = optimize.newton(g_x0,x0)
    b = optimize.newton(g_y0,y0)
    print 'cero del eje x =', a
    print 'cero del eje y =', b

ejemplo:


In [5]:
def g(x,y):
    return (x**2 - 2)*(y**2 - 3)

In [6]:
ceros(g,1,1)

cero del eje x = 1.41421356237
cero del eje y = 1.73205080757
